name: driven_site_locator
description: A new Flutter plugin project.
version: 0.0.2
homepage:

publish_to: 'none'
environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  app_settings: ^4.2.1
  cron: ^0.5.1
  dio: ^4.0.6
  driven_common:
    git:
      url: https://github.com/3FramesLab/flutter_driven-common
      # ref: feature/driven-common-base
      ref: feature/fix-sitelocator-api-cors
      version: ^0.0.2
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_google_maps_cluster:
    git:
      url: https://github.com/3FramesLab/flutter_google_maps_cluster
      ref: main
      version: ^0.0.6
  gauge_indicator: ^0.4.3
  geolocator: ^11.0.0
  get: ^4.6.5
  google_maps_flutter: ^2.2.3
  http: ^0.13.3
  map_launcher: ^2.4.0
  path_provider: ^2.0.15
  plugin_platform_interface: ^2.0.2
  pointer_interceptor: ^0.9.3+5
  sliding_up_panel: ^2.0.0+1
  

      
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.fleetcor.sitelocator.driven_site_locator
        pluginClass: DrivenSiteLocatorPlugin
      ios:
        pluginClass: DrivenSiteLocatorPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/site_locator/
    - assets/site_locator/2.0x/
    - assets/site_locator/3.0x/
    - assets/site_locator/comdata/
    - assets/site_locator/web/

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
