import 'package:driven_site_locator/data/model/app_utils.dart';

final Map<String, String> fuelAllBrandsListSource =
    AppUtils.isComdata ? comdataBrandsListSource : fuelmanBrandsListSource;

final Map<String, String> fuelmanBrandsListSource = {
  '76': '76',
  '7-eleven': '7-Eleven',
  'aamco': 'AAMCO',
  'alon': 'Alon',
  'amoco': 'Amoco',
  'arco': 'Arco',
  'bp': 'BP',
  'caseys': 'Caseys',
  'cenex': 'Cenex',
  'certified oil': 'Certified Oil',
  'chevron': 'Chevron',
  'circle k': 'Circle K',
  'citgo': 'Citgo',
  'clark': 'Clark',
  'conoco': 'Conoco',
  'corner store': 'Corner Store',
  'countrymark': 'CountryMark',
  'diamond shamrock': 'Diamond Shamrock',
  'exxon': 'Exxon',
  'firestone national acct': 'Firestone',
  'flying j': 'Flying J',
  'fuelman': 'Fuelman',
  'getgo': 'GetGo',
  'giant': 'Giant',
  'gulf': 'Gulf',
  'hess': 'Hess',
  'jiffy lube': 'Jiffy Lube',
  'kangaroo': 'Kangaroo',
  'kum & go': 'Kum & Go',
  'kwik shop': 'Kwik Shop',
  'kwik star': 'Kwik Star',
  'kwik trip': 'Kwik Trip',
  'loves': 'Loves',
  'mapco': 'Mapco',
  'marathon': 'Marathon',
  'maverik': 'Maverik',
  'meineke': 'Meineke',
  'mfa': 'MFA',
  'mobil': 'Mobil',
  'murphy': 'Murphy',
  'ntb': 'NTB',
  'phillips': 'Phillips',
  'pilot': 'Pilot',
  'quiktrip': 'QuikTrip',
  'racetrac': 'RaceTrac',
  'royal farms': 'Royal Farms',
  'rutters': 'Rutters',
  'sams club': 'Sams Club',
  'sheetz': 'Sheetz',
  'shell': 'Shell',
  'sinclair': 'Sinclair',
  'speedway': 'Speedway',
  'spinx': 'Spinx',
  'stripes': 'Stripes',
  'sunoco': 'Sunoco',
  'ta': 'TA',
  'tesoro': 'Tesoro',
  'texaco': 'Texaco',
  'thorntons': 'Thorntons',
  'tire kingdom': 'Tire Kingdom',
  'valero': 'Valero',
  'valvoline': 'Valvoline',
  'walmart': 'Walmart',
  'wawa': 'Wawa',
  'wesco': 'Wesco',
};

final Map<String, String> comdataBrandsListSource = {
  'pilot': 'Pilot',
  'loves': "Love's",
  'ta': 'TA',
  'speedway': 'Speedway',
  '7-eleven': '7-Eleven',
  'allsups': "Allsup's",
  'caseys': 'Caseys',
  'cefco': 'CEFCO',
  'certified oil': 'Certified Oil',
  'cfn': 'CFN',
  'circle k': 'Circle K',
  'clean energy': 'Clean Energy',
  'cubbys': "Cubby's",
  'esso': 'Esso',
  'flying j': 'Flying J',
  'gulf': 'Gulf',
  'husky': 'Husky',
  'kum & go': 'Kum & Go',
  'kwik trip': 'Kwik Trip',
  'mapco': 'Mapco',
  'mcclure oil': 'McClure Oil',
  'one9': 'One9',
  'petro stopping centers': 'Petro Stopping Centers',
  'petro-canada': 'Petro-Cananda',
  'petroleum wholesale': 'Petroleum Wholesale',
  'pump & pantry': 'Pump & Pantry',
  'quiktrip': 'QuikTrip',
  'racetrac': 'RaceTrac',
  'road ranger': 'Road Ranger',
  'royal farms': 'Royal Farms',
  'rutters': 'Rutters',
  'sapp bros': 'Sapp Bros',
  'sheetz': 'Sheetz',
  'spinx': 'Spinx',
  'stripes': 'Stripes',
  'thorntons': 'Thorntons',
};
