library map_view_module;

import 'dart:async';
import 'dart:math';

import 'package:cron/cron.dart';
import 'package:driven_site_locator/analytics/analytics.dart';
import 'package:driven_site_locator/config/globals.dart';
<<<<<<< HEAD
import 'package:driven_site_locator/data/data_sources/remote/decodable.dart';
=======
import 'package:driven_site_locator/config/sl_session_manager.dart';
>>>>>>> 3311a32b694c1aeb17c60419737b5f98abe6fb0d
import 'package:driven_site_locator/data/data_sources/remote/dynatrace_logs_tracking.dart';
import 'package:driven_site_locator/data/model/app_utils.dart';
import 'package:driven_site_locator/data/model/entitlement_repository.dart';
import 'package:driven_site_locator/driven_components/driven_components.dart';
import 'package:driven_site_locator/new_site_locator/data/services/site_locations_service.dart';
import 'package:driven_site_locator/new_site_locator/new_site_locator_module.dart';
import 'package:driven_site_locator/use_cases/base_future_usecase.dart';
import 'package:driven_site_locator/use_cases/base_usecase.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/services.dart';
import 'package:geolocator/geolocator.dart';
import 'package:get/get.dart';
import 'package:google_maps_cluster_manager_2/google_maps_cluster_manager_2.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart'
    hide ClusterManager, Cluster;
import 'package:permission_handler/permission_handler.dart';
import 'package:sliding_up_panel2/sliding_up_panel2.dart';

part 'controllers/site_locator_controller.dart';
part 'models/card_type_mapping.dart';
part 'models/enum_values.dart';
part 'models/fuel_prices.dart';
part 'models/site_location.dart';
part 'models/site_map_marker.dart';
part 'pages/unauth_sl_map_view_page.dart';
part 'site_locator_state.dart';
part 'use_cases/adjust_duplicate_lat_lng_use_case.dart';
part 'use_cases/apply_cluster_use_case.dart';
part 'use_cases/filter_markers_use_case.dart';
part 'use_cases/generate_markers_use_case.dart';
part 'use_cases/generate_site_hashmap_use_case.dart';
part 'use_cases/get_card_accepted_use_case.dart';
part 'use_cases/get_map_zoom_level_use_case.dart';
part 'use_cases/get_site_list_from_site_locations_use_case.dart';
part 'use_cases/get_site_locations_in_visible_map_region_use_case.dart';
part 'use_cases/get_site_source_from_card_type_use_case.dart';
part 'use_cases/get_user_location_use_case.dart';
part 'use_cases/lowest_fuel_price/get_lowest_fuel_price_use_case.dart';
part 'use_cases/lowest_fuel_price/get_sites_with_lowest_fuel_price_use_case.dart';
part 'use_cases/update_marker_icon_use_case.dart';
part 'widgets/custom_login_signup_button.dart';
part 'widgets/dialogs/share_my_location_dialog.dart';
part 'widgets/floating_map_button.dart';
part 'widgets/map_action_buttons.dart';
part 'widgets/new_gps_icon_button.dart';
part 'widgets/search_icon_button.dart';
part 'widgets/search_this_are_button_with_loader.dart';
part 'widgets/search_this_area_button.dart';
part 'widgets/shimmers/add_new_card_skeleton.dart';
part 'widgets/shimmers/fuel_card_list_view_skeleton.dart';
part 'widgets/site_info_popup.dart';
part 'widgets/site_info_popup_contents/a_discounted_price.dart';
part 'widgets/site_info_popup_contents/a_site_info_panel_header.dart';
part 'widgets/site_info_popup_contents/apply_for_comdata_card.dart';
part 'widgets/site_info_popup_contents/b_gallon_preferred_site.dart';
part 'widgets/site_info_popup_contents/c_site_miles_away.dart';
part 'widgets/site_info_popup_contents/d_site_address.dart';
part 'widgets/site_info_popup_contents/site_info_action_buttons.dart';
part 'widgets/site_info_popup_contents/site_info_popup_bottom_content.dart';
part 'widgets/site_info_popup_contents/site_info_popup_middle_content.dart';
part 'widgets/site_info_popup_contents/site_info_popup_top_content.dart';
part 'widgets/site_info_popup_contents/z_gallon_preferred_dialog.dart';
part 'widgets/site_locator_map_ui.dart';
